In [13]:
import pandas as pd

In [14]:
from quilt.data.robnewman import payments

In [17]:
df = payments.payments()

In [18]:
df

,payment_id,customer_id,staff_id,rental_id,amount,payment_date
0,16050,269,2,7,1.99,2017-01-24 21:40:19.996577-08
1,16051,269,1,98,0.99,2017-01-25 15:16:50.996577-08
2,16052,269,2,678,6.99,2017-01-28 21:44:14.996577-08
3,16053,269,2,703,0.99,2017-01-29 00:58:02.996577-08
4,16054,269,1,750,4.99,2017-01-29 08:10:06.996577-08
5,16055,269,2,1099,2.99,2017-01-31 12:23:14.996577-08
6,16056,270,1,193,1.99,2017-01-26 05:10:14.996577-08
7,16057,270,1,1040,4.99,2017-01-31 04:03:42.996577-08
8,16058,271,1,1096,8.99,2017-01-31 11:59:15.996577-08
9,16059,272,1,33,0.99,2017-01-25 02:47:17.996577-08
10,16060,272,1,405,6.99,2017-01-27 12:01:05.996577-08
11,16061,272,1,1041,6.99,2017-01-31 04:14:49.996577-08
12,16062,272,1,1072,0.99,2017-01-31 08:21:16.996577-08
13,16063,273,2,122,3.99,2017-01-25 18:14:47.996577-08
14,16064,273,2,980,0.99,2017-01-30 20:13:45.996577-08
15,16065,274,1,147,2.99,2017-01-25 22:46:16.996577-08
16,16066,274,1,208,4.99,2017-01-26 06:38:48.996577-08
17,16067,274,2,301,2.99,2017-01-26 19:34:40.996577-08
18,16068,274,1,394,5.99,2017-01-27 09:54:37.996577-08
19,16069,274,2,474,2.99,2017-01-27 20:40:22.996577-08
20,16070,274,1,892,4.99,2017-01-30 06:31:22.996577-08
21,16071,275,2,336,2.99,2017-01-27 01:43:49.996577-08
22,16072,276,1,736,3.99,2017-01-29 06:38:33.996577-08
23,16073,276,1,860,10.99,2017-01-30 01:13:42.996577-08
24,16074,277,2,308,6.99,2017-01-26 20:30:05.996577-08
25,16075,278,1,1092,4.99,2017-01-31 10:44:23.996577-08
26,16076,279,1,979,2.99,2017-01-30 20:05:37.996577-08
27,16077,279,2,1019,0.99,2017-01-31 01:33:33.996577-08
28,16078,280,1,1014,4.99,2017-01-31 01:07:42.996577-08
29,16079,281,2,650,2.99,2017-01-28 18:14:06.996577-08
...,...,...,...,...,...,...
15605,32069,181,2,13008,2.99,2017-05-14 13:44:29.996577-07
15606,32070,186,1,14216,2.99,2017-05-14 13:44:29.996577-07
15607,32071,188,1,14503,2.99,2017-05-14 13:44:29.996577-07
15608,32072,190,2,15167,4.99,2017-05-14 13:44:29.996577-07
15609,32073,191,1,14361,0.99,2017-05-14 13:44:29.996577-07
15610,32074,192,1,11611,4.99,2017-05-14 13:44:29.996577-07
15611,32075,193,2,15729,2.99,2017-05-14 13:44:29.996577-07
15612,32076,199,2,13952,2.99,2017-05-14 13:44:29.996577-07
15613,32077,200,2,11866,2.99,2017-05-14 13:44:29.996577-07
15614,32078,208,1,13719,5.98,2017-05-14 13:44:29.996577-07
15615,32079,208,1,15717,0.00,2017-05-14 13:44:29.996577-07
15616,32080,211,2,12746,4.99,2017-05-14 13:44:29.996577-07
15617,32081,213,2,14374,2.99,2017-05-14 13:44:29.996577-07
15618,32082,214,2,15645,2.99,2017-05-14 13:44:29.996577-07
15619,32083,215,2,15862,0.99,2017-05-14 13:44:29.996577-07
15620,32084,216,1,12970,5.98,2017-05-14 13:44:29.996577-07
15621,32085,216,1,11676,0.00,2017-05-14 13:44:29.996577-07
15622,32086,219,1,11577,4.99,2017-05-14 13:44:29.996577-07
15623,32087,227,2,13374,4.99,2017-05-14 13:44:29.996577-07
15624,32088,228,2,12672,3.98,2017-05-14 13:44:29.996577-07
15625,32089,228,1,15234,0.00,2017-05-14 13:44:29.996577-07
15626,32090,229,2,13295,0.99,2017-05-14 13:44:29.996577-07
15627,32091,234,1,15778,0.99,2017-05-14 13:44:29.996577-07
15628,32092,236,1,12988,0.99,2017-05-14 13:44:29.996577-07
15629,32093,244,2,12736,4.99,2017-05-14 13:44:29.996577-07
15630,32094,245,2,12682,2.99,2017-05-14 13:44:29.996577-07
15631,32095,251,1,14107,0.99,2017-05-14 13:44:29.996577-07
15632,32096,252,2,13756,4.99,2017-05-14 13:44:29.996577-07
15633,32097,263,1,15293,0.99,2017-05-14 13:44:29.996577-07
15634,32098,264,2,14243,2.99,2017-05-14 13:44:29.996577-07