In [1]:
import pandas as pd

In [2]:
from quilt.data.robnewman import performance

In [3]:
performance.payments()

,payment_id,customer_id,staff_id,rental_id,amount,payment_date
0,16050,269,2,7,1.99,2017-01-24 21:40:19.996577-08
1,16051,269,1,98,0.99,2017-01-25 15:16:50.996577-08
2,16052,269,2,678,6.99,2017-01-28 21:44:14.996577-08
3,16053,269,2,703,0.99,2017-01-29 00:58:02.996577-08
4,16054,269,1,750,4.99,2017-01-29 08:10:06.996577-08
5,16055,269,2,1099,2.99,2017-01-31 12:23:14.996577-08
6,16056,270,1,193,1.99,2017-01-26 05:10:14.996577-08
7,16057,270,1,1040,4.99,2017-01-31 04:03:42.996577-08
8,16058,271,1,1096,8.99,2017-01-31 11:59:15.996577-08
9,16059,272,1,33,0.99,2017-01-25 02:47:17.996577-08
10,16060,272,1,405,6.99,2017-01-27 12:01:05.996577-08
11,16061,272,1,1041,6.99,2017-01-31 04:14:49.996577-08
12,16062,272,1,1072,0.99,2017-01-31 08:21:16.996577-08
13,16063,273,2,122,3.99,2017-01-25 18:14:47.996577-08
14,16064,273,2,980,0.99,2017-01-30 20:13:45.996577-08
15,16065,274,1,147,2.99,2017-01-25 22:46:16.996577-08
16,16066,274,1,208,4.99,2017-01-26 06:38:48.996577-08
17,16067,274,2,301,2.99,2017-01-26 19:34:40.996577-08
18,16068,274,1,394,5.99,2017-01-27 09:54:37.996577-08
19,16069,274,2,474,2.99,2017-01-27 20:40:22.996577-08
20,16070,274,1,892,4.99,2017-01-30 06:31:22.996577-08
21,16071,275,2,336,2.99,2017-01-27 01:43:49.996577-08
22,16072,276,1,736,3.99,2017-01-29 06:38:33.996577-08
23,16073,276,1,860,10.99,2017-01-30 01:13:42.996577-08
24,16074,277,2,308,6.99,2017-01-26 20:30:05.996577-08
25,16075,278,1,1092,4.99,2017-01-31 10:44:23.996577-08
26,16076,279,1,979,2.99,2017-01-30 20:05:37.996577-08
27,16077,279,2,1019,0.99,2017-01-31 01:33:33.996577-08
28,16078,280,1,1014,4.99,2017-01-31 01:07:42.996577-08
29,16079,281,2,650,2.99,2017-01-28 18:14:06.996577-08
...,...,...,...,...,...,...
15605,32069,181,2,13008,2.99,2017-05-14 13:44:29.996577-07
15606,32070,186,1,14216,2.99,2017-05-14 13:44:29.996577-07
15607,32071,188,1,14503,2.99,2017-05-14 13:44:29.996577-07
15608,32072,190,2,15167,4.99,2017-05-14 13:44:29.996577-07
15609,32073,191,1,14361,0.99,2017-05-14 13:44:29.996577-07
15610,32074,192,1,11611,4.99,2017-05-14 13:44:29.996577-07
15611,32075,193,2,15729,2.99,2017-05-14 13:44:29.996577-07
15612,32076,199,2,13952,2.99,2017-05-14 13:44:29.996577-07
15613,32077,200,2,11866,2.99,2017-05-14 13:44:29.996577-07
15614,32078,208,1,13719,5.98,2017-05-14 13:44:29.996577-07
15615,32079,208,1,15717,0.00,2017-05-14 13:44:29.996577-07
15616,32080,211,2,12746,4.99,2017-05-14 13:44:29.996577-07
15617,32081,213,2,14374,2.99,2017-05-14 13:44:29.996577-07
15618,32082,214,2,15645,2.99,2017-05-14 13:44:29.996577-07
15619,32083,215,2,15862,0.99,2017-05-14 13:44:29.996577-07
15620,32084,216,1,12970,5.98,2017-05-14 13:44:29.996577-07
15621,32085,216,1,11676,0.00,2017-05-14 13:44:29.996577-07
15622,32086,219,1,11577,4.99,2017-05-14 13:44:29.996577-07
15623,32087,227,2,13374,4.99,2017-05-14 13:44:29.996577-07
15624,32088,228,2,12672,3.98,2017-05-14 13:44:29.996577-07
15625,32089,228,1,15234,0.00,2017-05-14 13:44:29.996577-07
15626,32090,229,2,13295,0.99,2017-05-14 13:44:29.996577-07
15627,32091,234,1,15778,0.99,2017-05-14 13:44:29.996577-07
15628,32092,236,1,12988,0.99,2017-05-14 13:44:29.996577-07
15629,32093,244,2,12736,4.99,2017-05-14 13:44:29.996577-07
15630,32094,245,2,12682,2.99,2017-05-14 13:44:29.996577-07
15631,32095,251,1,14107,0.99,2017-05-14 13:44:29.996577-07
15632,32096,252,2,13756,4.99,2017-05-14 13:44:29.996577-07
15633,32097,263,1,15293,0.99,2017-05-14 13:44:29.996577-07
15634,32098,264,2,14243,2.99,2017-05-14 13:44:29.996577-07

In [4]:
df_1 = performance.payments()

In [5]:
df_2 = performance.payments()

In [6]:
df_3 = performance.payments()

In [7]:
# FULL OUTER JOIN query
df_outer_join = performance.payments_outer_join()

In [8]:
# Display results
df_outer_join

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,customer_id.1,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,16050,269,2,7,1.99,2017-01-24 21:40:19.996577-08,269,1,CASSANDRA,WALTERS,CASSANDRA.WALTERS@sakilacustomer.org,274,t,2017-02-14,2017-02-15 09:57:20-08,1
1,16051,269,1,98,0.99,2017-01-25 15:16:50.996577-08,269,1,CASSANDRA,WALTERS,CASSANDRA.WALTERS@sakilacustomer.org,274,t,2017-02-14,2017-02-15 09:57:20-08,1
2,16052,269,2,678,6.99,2017-01-28 21:44:14.996577-08,269,1,CASSANDRA,WALTERS,CASSANDRA.WALTERS@sakilacustomer.org,274,t,2017-02-14,2017-02-15 09:57:20-08,1
3,16053,269,2,703,0.99,2017-01-29 00:58:02.996577-08,269,1,CASSANDRA,WALTERS,CASSANDRA.WALTERS@sakilacustomer.org,274,t,2017-02-14,2017-02-15 09:57:20-08,1
4,16054,269,1,750,4.99,2017-01-29 08:10:06.996577-08,269,1,CASSANDRA,WALTERS,CASSANDRA.WALTERS@sakilacustomer.org,274,t,2017-02-14,2017-02-15 09:57:20-08,1
5,16055,269,2,1099,2.99,2017-01-31 12:23:14.996577-08,269,1,CASSANDRA,WALTERS,CASSANDRA.WALTERS@sakilacustomer.org,274,t,2017-02-14,2017-02-15 09:57:20-08,1
6,16056,270,1,193,1.99,2017-01-26 05:10:14.996577-08,270,1,LEAH,CURTIS,LEAH.CURTIS@sakilacustomer.org,275,t,2017-02-14,2017-02-15 09:57:20-08,1
7,16057,270,1,1040,4.99,2017-01-31 04:03:42.996577-08,270,1,LEAH,CURTIS,LEAH.CURTIS@sakilacustomer.org,275,t,2017-02-14,2017-02-15 09:57:20-08,1
8,16058,271,1,1096,8.99,2017-01-31 11:59:15.996577-08,271,1,PENNY,NEAL,PENNY.NEAL@sakilacustomer.org,276,t,2017-02-14,2017-02-15 09:57:20-08,0
9,16059,272,1,33,0.99,2017-01-25 02:47:17.996577-08,272,1,KAY,CALDWELL,KAY.CALDWELL@sakilacustomer.org,277,t,2017-02-14,2017-02-15 09:57:20-08,1
10,16060,272,1,405,6.99,2017-01-27 12:01:05.996577-08,272,1,KAY,CALDWELL,KAY.CALDWELL@sakilacustomer.org,277,t,2017-02-14,2017-02-15 09:57:20-08,1
11,16061,272,1,1041,6.99,2017-01-31 04:14:49.996577-08,272,1,KAY,CALDWELL,KAY.CALDWELL@sakilacustomer.org,277,t,2017-02-14,2017-02-15 09:57:20-08,1
12,16062,272,1,1072,0.99,2017-01-31 08:21:16.996577-08,272,1,KAY,CALDWELL,KAY.CALDWELL@sakilacustomer.org,277,t,2017-02-14,2017-02-15 09:57:20-08,1
13,16063,273,2,122,3.99,2017-01-25 18:14:47.996577-08,273,2,PRISCILLA,LOWE,PRISCILLA.LOWE@sakilacustomer.org,278,t,2017-02-14,2017-02-15 09:57:20-08,1
14,16064,273,2,980,0.99,2017-01-30 20:13:45.996577-08,273,2,PRISCILLA,LOWE,PRISCILLA.LOWE@sakilacustomer.org,278,t,2017-02-14,2017-02-15 09:57:20-08,1
15,16065,274,1,147,2.99,2017-01-25 22:46:16.996577-08,274,1,NAOMI,JENNINGS,NAOMI.JENNINGS@sakilacustomer.org,279,t,2017-02-14,2017-02-15 09:57:20-08,1
16,16066,274,1,208,4.99,2017-01-26 06:38:48.996577-08,274,1,NAOMI,JENNINGS,NAOMI.JENNINGS@sakilacustomer.org,279,t,2017-02-14,2017-02-15 09:57:20-08,1
17,16067,274,2,301,2.99,2017-01-26 19:34:40.996577-08,274,1,NAOMI,JENNINGS,NAOMI.JENNINGS@sakilacustomer.org,279,t,2017-02-14,2017-02-15 09:57:20-08,1
18,16068,274,1,394,5.99,2017-01-27 09:54:37.996577-08,274,1,NAOMI,JENNINGS,NAOMI.JENNINGS@sakilacustomer.org,279,t,2017-02-14,2017-02-15 09:57:20-08,1
19,16069,274,2,474,2.99,2017-01-27 20:40:22.996577-08,274,1,NAOMI,JENNINGS,NAOMI.JENNINGS@sakilacustomer.org,279,t,2017-02-14,2017-02-15 09:57:20-08,1
20,16070,274,1,892,4.99,2017-01-30 06:31:22.996577-08,274,1,NAOMI,JENNINGS,NAOMI.JENNINGS@sakilacustomer.org,279,t,2017-02-14,2017-02-15 09:57:20-08,1
21,16071,275,2,336,2.99,2017-01-27 01:43:49.996577-08,275,2,CAROLE,BARNETT,CAROLE.BARNETT@sakilacustomer.org,280,t,2017-02-14,2017-02-15 09:57:20-08,1
22,16072,276,1,736,3.99,2017-01-29 06:38:33.996577-08,276,1,BRANDY,GRAVES,BRANDY.GRAVES@sakilacustomer.org,281,t,2017-02-14,2017-02-15 09:57:20-08,1
23,16073,276,1,860,10.99,2017-01-30 01:13:42.996577-08,276,1,BRANDY,GRAVES,BRANDY.GRAVES@sakilacustomer.org,281,t,2017-02-14,2017-02-15 09:57:20-08,1
24,16074,277,2,308,6.99,2017-01-26 20:30:05.996577-08,277,2,OLGA,JIMENEZ,OLGA.JIMENEZ@sakilacustomer.org,282,t,2017-02-14,2017-02-15 09:57:20-08,1
25,16075,278,1,1092,4.99,2017-01-31 10:44:23.996577-08,278,2,BILLIE,HORTON,BILLIE.HORTON@sakilacustomer.org,283,t,2017-02-14,2017-02-15 09:57:20-08,1
26,16076,279,1,979,2.99,2017-01-30 20:05:37.996577-08,279,2,DIANNE,SHELTON,DIANNE.SHELTON@sakilacustomer.org,284,t,2017-02-14,2017-02-15 09:57:20-08,1
27,16077,279,2,1019,0.99,2017-01-31 01:33:33.996577-08,279,2,DIANNE,SHELTON,DIANNE.SHELTON@sakilacustomer.org,284,t,2017-02-14,2017-02-15 09:57:20-08,1
28,16078,280,1,1014,4.99,2017-01-31 01:07:42.996577-08,280,2,TRACEY,BARRETT,TRACEY.BARRETT@sakilacustomer.org,285,t,2017-02-14,2017-02-15 09:57:20-08,1
29,16079,281,2,650,2.99,2017-01-28 18:14:06.996577-08,281,2,LEONA,OBRIEN,LEONA.OBRIEN@sakilacustomer.org,286,t,2017-02-14,2017-02-15 09:57:20-08,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15605,32069,181,2,13008,2.99,2017-05-14 13:44:29.996577-07,181,2,ANA,BRADLEY,ANA.BRADLEY@sakilacustomer.org,185,t,2017-02-14,2017-02-15 09:57:20-08,1
15606,32070,186,1,14216,2.99,2017-05-14 13:44:29.996577-07,186,2,HOLLY,FOX,HOLLY.FOX@sakilacustomer.org,190,t,2017-02-14,2017-02-15 09:57:20-08,1
15607,32071,188,1,14503,2.99,2017-05-14 13:44:29.996577-07,188,1,MELANIE,ARMSTRONG,MELANIE.ARMSTRONG@sakilacustomer.org,192,t,2017-02-14,2017-02-15 09:57:20-08,1
15608,32072,190,2,15167,4.99,2017-05-14 13:44:29.996577-07,190,2,YOLANDA,WEAVER,YOLANDA.WEAVER@sakilacustomer.org,194,t,2017-02-14,2017-02-15 09:57:20-08,1
15609,32073,191,1,14361,0.99,2017-05-14 13:44:29.996577-07,191,1,JEANETTE,GREENE,JEANETTE.GREENE@sakilacustomer.org,195,t,2017-02-14,2017-02-15 09:57:20-08,1
15610,32074,192,1,11611,4.99,2017-05-14 13:44:29.996577-07,192,1,LAURIE,LAWRENCE,LAURIE.LAWRENCE@sakilacustomer.org,196,t,2017-02-14,2017-02-15 09:57:20-08,1
15611,32075,193,2,15729,2.99,2017-05-14 13:44:29.996577-07,193,2,KATIE,ELLIOTT,KATIE.ELLIOTT@sakilacustomer.org,197,t,2017-02-14,2017-02-15 09:57:20-08,1
15612,32076,199,2,13952,2.99,2017-05-14 13:44:29.996577-07,199,2,BETH,FRANKLIN,BETH.FRANKLIN@sakilacustomer.org,203,t,2017-02-14,2017-02-15 09:57:20-08,1
15613,32077,200,2,11866,2.99,2017-05-14 13:44:29.996577-07,200,2,JEANNE,LAWSON,JEANNE.LAWSON@sakilacustomer.org,204,t,2017-02-14,2017-02-15 09:57:20-08,1
15614,32078,208,1,13719,5.98,2017-05-14 13:44:29.996577-07,208,1,LUCY,WHEELER,LUCY.WHEELER@sakilacustomer.org,212,t,2017-02-14,2017-02-15 09:57:20-08,1
15615,32079,208,1,15717,0.00,2017-05-14 13:44:29.996577-07,208,1,LUCY,WHEELER,LUCY.WHEELER@sakilacustomer.org,212,t,2017-02-14,2017-02-15 09:57:20-08,1
15616,32080,211,2,12746,4.99,2017-05-14 13:44:29.996577-07,211,1,STACEY,MONTGOMERY,STACEY.MONTGOMERY@sakilacustomer.org,215,t,2017-02-14,2017-02-15 09:57:20-08,1
15617,32081,213,2,14374,2.99,2017-05-14 13:44:29.996577-07,213,1,GINA,WILLIAMSON,GINA.WILLIAMSON@sakilacustomer.org,217,t,2017-02-14,2017-02-15 09:57:20-08,1
15618,32082,214,2,15645,2.99,2017-05-14 13:44:29.996577-07,214,1,KRISTIN,JOHNSTON,KRISTIN.JOHNSTON@sakilacustomer.org,218,t,2017-02-14,2017-02-15 09:57:20-08,1
15619,32083,215,2,15862,0.99,2017-05-14 13:44:29.996577-07,215,2,JESSIE,BANKS,JESSIE.BANKS@sakilacustomer.org,219,t,2017-02-14,2017-02-15 09:57:20-08,1
15620,32084,216,1,12970,5.98,2017-05-14 13:44:29.996577-07,216,1,NATALIE,MEYER,NATALIE.MEYER@sakilacustomer.org,220,t,2017-02-14,2017-02-15 09:57:20-08,1
15621,32085,216,1,11676,0.00,2017-05-14 13:44:29.996577-07,216,1,NATALIE,MEYER,NATALIE.MEYER@sakilacustomer.org,220,t,2017-02-14,2017-02-15 09:57:20-08,1
15622,32086,219,1,11577,4.99,2017-05-14 13:44:29.996577-07,219,2,WILLIE,HOWELL,WILLIE.HOWELL@sakilacustomer.org,223,t,2017-02-14,2017-02-15 09:57:20-08,1
15623,32087,227,2,13374,4.99,2017-05-14 13:44:29.996577-07,227,1,COLLEEN,BURTON,COLLEEN.BURTON@sakilacustomer.org,231,t,2017-02-14,2017-02-15 09:57:20-08,1
15624,32088,228,2,12672,3.98,2017-05-14 13:44:29.996577-07,228,2,ALLISON,STANLEY,ALLISON.STANLEY@sakilacustomer.org,232,t,2017-02-14,2017-02-15 09:57:20-08,1
15625,32089,228,1,15234,0.00,2017-05-14 13:44:29.996577-07,228,2,ALLISON,STANLEY,ALLISON.STANLEY@sakilacustomer.org,232,t,2017-02-14,2017-02-15 09:57:20-08,1
15626,32090,229,2,13295,0.99,2017-05-14 13:44:29.996577-07,229,1,TAMARA,NGUYEN,TAMARA.NGUYEN@sakilacustomer.org,233,t,2017-02-14,2017-02-15 09:57:20-08,1
15627,32091,234,1,15778,0.99,2017-05-14 13:44:29.996577-07,234,1,CLAUDIA,FULLER,CLAUDIA.FULLER@sakilacustomer.org,238,t,2017-02-14,2017-02-15 09:57:20-08,1
15628,32092,236,1,12988,0.99,2017-05-14 13:44:29.996577-07,236,1,MARCIA,DEAN,MARCIA.DEAN@sakilacustomer.org,240,t,2017-02-14,2017-02-15 09:57:20-08,1
15629,32093,244,2,12736,4.99,2017-05-14 13:44:29.996577-07,244,2,VIOLA,HANSON,VIOLA.HANSON@sakilacustomer.org,248,t,2017-02-14,2017-02-15 09:57:20-08,1
15630,32094,245,2,12682,2.99,2017-05-14 13:44:29.996577-07,245,1,COURTNEY,DAY,COURTNEY.DAY@sakilacustomer.org,249,t,2017-02-14,2017-02-15 09:57:20-08,1
15631,32095,251,1,14107,0.99,2017-05-14 13:44:29.996577-07,251,2,VICKIE,BREWER,VICKIE.BREWER@sakilacustomer.org,255,t,2017-02-14,2017-02-15 09:57:20-08,1
15632,32096,252,2,13756,4.99,2017-05-14 13:44:29.996577-07,252,2,MATTIE,HOFFMAN,MATTIE.HOFFMAN@sakilacustomer.org,256,t,2017-02-14,2017-02-15 09:57:20-08,1
15633,32097,263,1,15293,0.99,2017-05-14 13:44:29.996577-07,263,1,HILDA,HOPKINS,HILDA.HOPKINS@sakilacustomer.org,268,t,2017-02-14,2017-02-15 09:57:20-08,1
15634,32098,264,2,14243,2.99,2017-05-14 13:44:29.996577-07,264,1,GWENDOLYN,MAY,GWENDOLYN.MAY@sakilacustomer.org,269,t,2017-02-14,2017-02-15 09:57:20-08,1

In [10]:
# FULL OUTER JOIN query result
df_outer_join = performance.payments_large_outer_join()

In [11]:
df_outer_join

,payment_id,customer_id,staff_id,rental_id,amount,payment_date,customer_id.1,store_id,first_name,last_name,...,postal_code,phone,last_update.2,rental_id.1,rental_date,inventory_id,customer_id.2,return_date,staff_id.1,last_update.3
0,16050.0,269.0,2.0,7.0,1.99,2017-01-24 21:40:19.996577-08,269.0,1.0,CASSANDRA,WALTERS,...,75090.0,6.850107e+11,2017-02-15 09:45:30-08,7.0,2005-05-24 23:11:53-07,3995.0,269.0,2005-05-29 20:34:53-07,2.0,2017-02-16 02:30:53-08
1,16051.0,269.0,1.0,98.0,0.99,2017-01-25 15:16:50.996577-08,269.0,1.0,CASSANDRA,WALTERS,...,75090.0,6.850107e+11,2017-02-15 09:45:30-08,98.0,2005-05-25 16:48:24-07,2970.0,269.0,2005-05-27 11:29:24-07,2.0,2017-02-16 02:30:53-08
2,16052.0,269.0,2.0,678.0,6.99,2017-01-28 21:44:14.996577-08,269.0,1.0,CASSANDRA,WALTERS,...,75090.0,6.850107e+11,2017-02-15 09:45:30-08,678.0,2005-05-28 23:15:48-07,3741.0,269.0,2005-06-03 04:43:48-07,2.0,2017-02-16 02:30:53-08
3,16053.0,269.0,2.0,703.0,0.99,2017-01-29 00:58:02.996577-08,269.0,1.0,CASSANDRA,WALTERS,...,75090.0,6.850107e+11,2017-02-15 09:45:30-08,703.0,2005-05-29 02:29:36-07,1123.0,269.0,2005-06-03 04:54:36-07,2.0,2017-02-16 02:30:53-08
4,16054.0,269.0,1.0,750.0,4.99,2017-01-29 08:10:06.996577-08,269.0,1.0,CASSANDRA,WALTERS,...,75090.0,6.850107e+11,2017-02-15 09:45:30-08,750.0,2005-05-29 09:41:40-07,730.0,269.0,2005-05-30 13:31:40-07,1.0,2017-02-16 02:30:53-08
5,16055.0,269.0,2.0,1099.0,2.99,2017-01-31 12:23:14.996577-08,269.0,1.0,CASSANDRA,WALTERS,...,75090.0,6.850107e+11,2017-02-15 09:45:30-08,1099.0,2005-05-31 13:54:48-07,924.0,269.0,2005-06-05 13:04:48-07,2.0,2017-02-16 02:30:53-08
6,16056.0,270.0,1.0,193.0,1.99,2017-01-26 05:10:14.996577-08,270.0,1.0,LEAH,CURTIS,...,83565.0,7.017676e+11,2017-02-15 09:45:30-08,193.0,2005-05-26 06:41:48-07,3900.0,270.0,2005-05-30 06:21:48-07,2.0,2017-02-16 02:30:53-08
7,16057.0,270.0,1.0,1040.0,4.99,2017-01-31 04:03:42.996577-08,270.0,1.0,LEAH,CURTIS,...,83565.0,7.017676e+11,2017-02-15 09:45:30-08,1040.0,2005-05-31 05:35:16-07,2546.0,270.0,2005-06-09 04:14:16-07,1.0,2017-02-16 02:30:53-08
8,16058.0,271.0,1.0,1096.0,8.99,2017-01-31 11:59:15.996577-08,271.0,1.0,PENNY,NEAL,...,11763.0,2.711495e+11,2017-02-15 09:45:30-08,1096.0,2005-05-31 13:30:49-07,1066.0,271.0,2005-06-09 13:53:49-07,1.0,2017-02-16 02:30:53-08
9,16059.0,272.0,1.0,33.0,0.99,2017-01-25 02:47:17.996577-08,272.0,1.0,KAY,CALDWELL,...,46063.0,1.707396e+11,2017-02-15 09:45:30-08,33.0,2005-05-25 04:18:51-07,1681.0,272.0,2005-05-27 03:58:51-07,1.0,2017-02-16 02:30:53-08
10,16060.0,272.0,1.0,405.0,6.99,2017-01-27 12:01:05.996577-08,272.0,1.0,KAY,CALDWELL,...,46063.0,1.707396e+11,2017-02-15 09:45:30-08,405.0,2005-05-27 13:32:39-07,4090.0,272.0,2005-06-05 18:53:39-07,2.0,2017-02-16 02:30:53-08
11,16061.0,272.0,1.0,1041.0,6.99,2017-01-31 04:14:49.996577-08,272.0,1.0,KAY,CALDWELL,...,46063.0,1.707396e+11,2017-02-15 09:45:30-08,1041.0,2005-05-31 05:46:23-07,4432.0,272.0,2005-06-06 09:50:23-07,2.0,2017-02-16 02:30:53-08
12,16062.0,272.0,1.0,1072.0,0.99,2017-01-31 08:21:16.996577-08,272.0,1.0,KAY,CALDWELL,...,46063.0,1.707396e+11,2017-02-15 09:45:30-08,1072.0,2005-05-31 09:52:50-07,2557.0,272.0,2005-06-05 05:39:50-07,1.0,2017-02-16 02:30:53-08
13,16063.0,273.0,2.0,122.0,3.99,2017-01-25 18:14:47.996577-08,273.0,2.0,PRISCILLA,LOWE,...,2012.0,4.538729e+10,2017-02-15 09:45:30-08,122.0,2005-05-25 19:46:21-07,2908.0,273.0,2005-06-02 19:07:21-07,1.0,2017-02-16 02:30:53-08
14,16064.0,273.0,2.0,980.0,0.99,2017-01-30 20:13:45.996577-08,273.0,2.0,PRISCILLA,LOWE,...,2012.0,4.538729e+10,2017-02-15 09:45:30-08,980.0,2005-05-30 21:45:19-07,4169.0,273.0,2005-06-01 20:32:19-07,1.0,2017-02-16 02:30:53-08
15,16065.0,274.0,1.0,147.0,2.99,2017-01-25 22:46:16.996577-08,274.0,1.0,NAOMI,JENNINGS,...,85548.0,9.599494e+11,2017-02-15 09:45:30-08,147.0,2005-05-26 00:17:50-07,633.0,274.0,2005-05-29 23:21:50-07,2.0,2017-02-16 02:30:53-08
16,16066.0,274.0,1.0,208.0,4.99,2017-01-26 06:38:48.996577-08,274.0,1.0,NAOMI,JENNINGS,...,85548.0,9.599494e+11,2017-02-15 09:45:30-08,208.0,2005-05-26 08:10:22-07,3669.0,274.0,2005-05-27 03:55:22-07,1.0,2017-02-16 02:30:53-08
17,16067.0,274.0,2.0,301.0,2.99,2017-01-26 19:34:40.996577-08,274.0,1.0,NAOMI,JENNINGS,...,85548.0,9.599494e+11,2017-02-15 09:45:30-08,301.0,2005-05-26 21:06:14-07,3448.0,274.0,2005-06-01 01:54:14-07,2.0,2017-02-16 02:30:53-08
18,16068.0,274.0,1.0,394.0,5.99,2017-01-27 09:54:37.996577-08,274.0,1.0,NAOMI,JENNINGS,...,85548.0,9.599494e+11,2017-02-15 09:45:30-08,394.0,2005-05-27 11:26:11-07,1890.0,274.0,2005-06-03 16:44:11-07,2.0,2017-02-16 02:30:53-08
19,16069.0,274.0,2.0,474.0,2.99,2017-01-27 20:40:22.996577-08,274.0,1.0,NAOMI,JENNINGS,...,85548.0,9.599494e+11,2017-02-15 09:45:30-08,474.0,2005-05-27 22:11:56-07,1474.0,274.0,2005-05-31 19:07:56-07,1.0,2017-02-16 02:30:53-08
20,16070.0,274.0,1.0,892.0,4.99,2017-01-30 06:31:22.996577-08,274.0,1.0,NAOMI,JENNINGS,...,85548.0,9.599494e+11,2017-02-15 09:45:30-08,892.0,2005-05-30 08:02:56-07,471.0,274.0,2005-06-05 12:51:56-07,1.0,2017-02-16 02:30:53-08
21,16071.0,275.0,2.0,336.0,2.99,2017-01-27 01:43:49.996577-08,275.0,2.0,CAROLE,BARNETT,...,89502.0,8.743371e+11,2017-02-15 09:45:30-08,336.0,2005-05-27 03:15:23-07,1811.0,275.0,2005-05-29 22:43:23-07,1.0,2017-02-16 02:30:53-08
22,16072.0,276.0,1.0,736.0,3.99,2017-01-29 06:38:33.996577-08,276.0,1.0,BRANDY,GRAVES,...,24645.0,7.597522e+10,2017-02-15 09:45:30-08,736.0,2005-05-29 08:10:07-07,3689.0,276.0,2005-06-05 10:21:07-07,2.0,2017-02-16 02:30:53-08
23,16073.0,276.0,1.0,860.0,10.99,2017-01-30 01:13:42.996577-08,276.0,1.0,BRANDY,GRAVES,...,24645.0,7.597522e+10,2017-02-15 09:45:30-08,860.0,2005-05-30 02:45:16-07,578.0,276.0,2005-06-08 07:28:16-07,1.0,2017-02-16 02:30:53-08
24,16074.0,277.0,2.0,308.0,6.99,2017-01-26 20:30:05.996577-08,277.0,2.0,OLGA,JIMENEZ,...,55802.0,3.639822e+11,2017-02-15 09:45:30-08,308.0,2005-05-26 22:01:39-07,187.0,277.0,2005-06-04 20:24:39-07,2.0,2017-02-16 02:30:53-08
25,16075.0,278.0,1.0,1092.0,4.99,2017-01-31 10:44:23.996577-08,278.0,2.0,BILLIE,HORTON,...,56254.0,8.807562e+11,2017-02-15 09:45:30-08,1092.0,2005-05-31 12:15:57-07,4412.0,278.0,2005-06-03 15:39:57-07,2.0,2017-02-16 02:30:53-08
26,16076.0,279.0,1.0,979.0,2.99,2017-01-30 20:05:37.996577-08,279.0,2.0,DIANNE,SHELTON,...,96204.0,1.175923e+11,2017-02-15 09:45:30-08,979.0,2005-05-30 21:37:11-07,3917.0,279.0,2005-06-08 00:24:11-07,2.0,2017-02-16 02:30:53-08
27,16077.0,279.0,2.0,1019.0,0.99,2017-01-31 01:33:33.996577-08,279.0,2.0,DIANNE,SHELTON,...,96204.0,1.175923e+11,2017-02-15 09:45:30-08,1019.0,2005-05-31 03:05:07-07,3975.0,279.0,2005-06-03 08:34:07-07,1.0,2017-02-16 02:30:53-08
28,16078.0,280.0,1.0,1014.0,4.99,2017-01-31 01:07:42.996577-08,280.0,2.0,TRACEY,BARRETT,...,36229.0,8.505974e+10,2017-02-15 09:45:30-08,1014.0,2005-05-31 02:39:16-07,766.0,280.0,2005-06-01 06:03:16-07,2.0,2017-02-16 02:30:53-08
29,16079.0,281.0,2.0,650.0,2.99,2017-01-28 18:14:06.996577-08,281.0,2.0,LEONA,OBRIEN,...,30657.0,5.830212e+11,2017-02-15 09:45:30-08,650.0,2005-05-28 19:45:40-07,4384.0,281.0,2005-05-29 21:02:40-07,1.0,2017-02-16 02:30:53-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16022,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10079.0,2005-07-31 20:05:45-07,4541.0,486.0,2005-08-04 16:25:45-07,2.0,2017-02-16 02:30:53-08
16023,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10181.0,2005-08-01 00:00:44-07,3111.0,113.0,2005-08-04 19:33:44-07,1.0,2017-02-16 02:30:53-08
16024,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9527.0,2005-07-31 01:02:24-07,2539.0,200.0,2005-08-09 02:08:24-07,2.0,2017-02-16 02:30:53-08
16025,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9423.0,2005-07-30 21:10:14-07,3145.0,242.0,2005-08-07 16:34:14-07,2.0,2017-02-16 02:30:53-08
16026,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10208.0,2005-08-01 00:54:51-07,3324.0,246.0,2005-08-04 22:39:51-07,2.0,2017-02-16 02:30:53-08
16027,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9398.0,2005-07-30 20:09:00-07,1175.0,570.0,2005-08-01 23:35:00-07,2.0,2017-02-16 02:30:53-08
16028,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9463.0,2005-07-30 22:30:57-07,883.0,352.0,2005-08-03 22:53:57-07,1.0,2017-02-16 02:30:53-08
16029,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9509.0,2005-07-31 00:22:42-07,818.0,320.0,2005-08-03 23:24:42-07,1.0,2017-02-16 02:30:53-08
16030,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9419.0,2005-07-30 21:04:59-07,4427.0,142.0,2005-08-06 15:47:59-07,2.0,2017-02-16 02:30:53-08
16031,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9461.0,2005-07-30 22:29:13-07,1679.0,377.0,2005-08-05 20:55:13-07,2.0,2017-02-16 02:30:53-08
16032,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10053.0,2005-07-31 19:15:39-07,4102.0,223.0,2005-08-07 22:32:39-07,1.0,2017-02-16 02:30:53-08
16033,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10148.0,2005-07-31 22:19:16-07,1381.0,63.0,2005-08-05 00:15:16-07,2.0,2017-02-16 02:30:53-08
16034,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10179.0,2005-07-31 23:49:54-07,2136.0,131.0,2005-08-01 20:46:54-07,2.0,2017-02-16 02:30:53-08
16035,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9354.0,2005-07-30 18:32:51-07,510.0,595.0,2005-08-02 21:28:51-07,2.0,2017-02-16 02:30:53-08
16036,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10064.0,2005-07-31 19:27:02-07,3140.0,41.0,2005-08-06 21:15:02-07,1.0,2017-02-16 02:30:53-08
16037,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9355.0,2005-07-30 18:35:25-07,1122.0,201.0,2005-08-03 20:33:25-07,2.0,2017-02-16 02:30:53-08
16038,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10120.0,2005-07-31 21:24:24-07,1709.0,396.0,2005-08-03 17:44:24-07,2.0,2017-02-16 02:30:53-08
16039,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10083.0,2005-07-31 20:10:19-07,2585.0,449.0,2005-08-06 23:18:19-07,1.0,2017-02-16 02:30:53-08
16040,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,1140.0,2005-05-31 19:36:30-07,3731.0,10.0,2005-06-07 18:33:30-07,2.0,2017-02-16 02:30:53-08
16041,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9531.0,2005-07-31 01:11:53-07,4550.0,268.0,2005-08-07 02:49:53-07,1.0,2017-02-16 02:30:53-08
16042,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9361.0,2005-07-30 18:43:49-07,4163.0,335.0,2005-08-06 21:24:49-07,1.0,2017-02-16 02:30:53-08
16043,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,1157.0,2005-05-31 22:47:45-07,1449.0,61.0,2005-06-02 18:01:45-07,1.0,2017-02-16 02:30:53-08
16044,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9400.0,2005-07-30 20:15:58-07,3910.0,368.0,2005-08-03 21:21:58-07,1.0,2017-02-16 02:30:53-08
16045,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9512.0,2005-07-31 00:26:30-07,3786.0,173.0,2005-08-04 23:43:30-07,2.0,2017-02-16 02:30:53-08
16046,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9401.0,2005-07-30 20:18:19-07,2057.0,331.0,2005-08-07 15:46:19-07,1.0,2017-02-16 02:30:53-08
16047,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9488.0,2005-07-30 23:42:42-07,4221.0,528.0,2005-08-08 22:15:42-07,1.0,2017-02-16 02:30:53-08
16048,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9376.0,2005-07-30 19:11:49-07,451.0,86.0,2005-08-04 18:14:49-07,1.0,2017-02-16 02:30:53-08
16049,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,1127.0,2005-05-31 17:45:49-07,2412.0,387.0,2005-06-08 22:41:49-07,2.0,2017-02-16 02:30:53-08
16050,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,10092.0,2005-07-31 20:28:09-07,4151.0,364.0,2005-08-01 21:37:09-07,1.0,2017-02-16 02:30:53-08
16051,NaN,NaN,NaN,NaN,NaN,nan,NaN,NaN,nan,nan,...,NaN,NaN,nan,9449.0,2005-07-30 22:02:34-07,2.0,581.0,2005-08-06 02:09:34-07,1.0,2017-02-16 02:30:53-08